### ISSUE TITLE
GTK issues on headless server

### ISSUE THREAD

**Issue by bogdanm** [PedroAlvesV/AbsTK#10]
I have an Ubuntu 16.04 VPS (headless, no GTK libs) on which I try to run a sample app that uses AbsTK. I'm getting this error:

```
$ lua temp.lua
lua: /usr/local/share/lua/5.1/lgi/namespace.lua:151: Typelib file for namespace 'Gtk' (any version) not found
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/lgi/namespace.lua:151: in function 'require'
        /usr/local/share/lua/5.1/abstk/AbsGtk.lua:13: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/abstk.lua:11: in main chunk
        [C]: in function 'require'
        temp.lua:1: in main chunk
        [C]: ?
```

`temp.lua` is just one of the sample apps:

```
local abstk = require 'abstk'
-- abstk.set_mode("curses")
local scr = abstk.new_screen("My First AbsTK UI")
scr:add_label('hellow', "Hello, World!")
scr:add_label('msg1', "This is a minimal example to demonstrate AbsTK.")
scr:add_label('msg2', "The Screen is the main object of the toolkit. It can run as standalone or added to a Wizard. Its routine consists in creating it (line 2), populating it (lines 3 to 7) and running it (line 8).")
scr:run()
```

It doesn't work even if I uncomment the second line, or if I run `lua temp.lua curses`. 

Trying to install the proper .typelib files for Gtk gets me into a whole lot of trouble, and dependencies that I don't really need on the VPS. AbsTK should probably give up on GTK when encountering this kind of error and switch to curses automatically.

**Comment by PedroAlvesV** [comment]
Well, I'm sorry for that. I accepted a pull request like 10 hours ago that was precisely about _handling missing modules_ (#9). This was the change: c1a8fd7
As I didn't like the way it was written, I rewrote it to this: 2bde481

I'll make a new release, but I think that running `luarocks install abstk` already does the job.

**Comment by bogdanm** [comment]
At the moment, I get the error above after running `lurocks install abstk`. I removed `abstk`, then installed it again just to make sure. Still getting the same error.

**Comment by PedroAlvesV** [comment]
Right. I just made the new release and updated it on LuaRocks. I've run a few tests without lgi and it worked. Could you reinstall the rock? I don't know if LuaRocks has a better option than removing it and reinstalling. All I know is that you can run `luarocks list --outdated` to see the outdated packages.

**Comment by bogdanm** [comment]
The GTK error is gone, thanks! I'm still not able to run the example, but that's very likely not related to GTK anymore, so I'm closing this.

**Comment by PedroAlvesV** [comment]
I'm glad to know it solved this problem :)
On this new issue, you can ask me anything! (Or open a new issue, if you think it's AbsTK fault)
